apiVersion: kind.sigs.k8s.io/v1alpha1
kind: Config
kubeadmConfigPatches:
- |
  apiVersion: kubeadm.k8s.io/v1beta1
  kind: ClusterConfiguration
  apiServer:
    extraArgs:
      audit-dynamic-configuration: "true"
      feature-gates: "DynamicAuditing=true"
      runtime-config: "auditregistration.k8s.io/v1alpha1=true"