/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
	auditregistration "k8s.io/kubernetes/pkg/apis/auditregistration"
)

// FakeAuditClasses implements AuditClassInterface
type FakeAuditClasses struct {
	Fake *FakeAuditregistration
}

var auditclassesResource = schema.GroupVersionResource{Group: "auditregistration.k8s.io", Version: "", Resource: "auditclasses"}

var auditclassesKind = schema.GroupVersionKind{Group: "auditregistration.k8s.io", Version: "", Kind: "AuditClass"}

// Get takes name of the auditClass, and returns the corresponding auditClass object, and an error if there is any.
func (c *FakeAuditClasses) Get(name string, options v1.GetOptions) (result *auditregistration.AuditClass, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootGetAction(auditclassesResource, name), &auditregistration.AuditClass{})
	if obj == nil {
		return nil, err
	}
	return obj.(*auditregistration.AuditClass), err
}

// List takes label and field selectors, and returns the list of AuditClasses that match those selectors.
func (c *FakeAuditClasses) List(opts v1.ListOptions) (result *auditregistration.AuditClassList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootListAction(auditclassesResource, auditclassesKind, opts), &auditregistration.AuditClassList{})
	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &auditregistration.AuditClassList{ListMeta: obj.(*auditregistration.AuditClassList).ListMeta}
	for _, item := range obj.(*auditregistration.AuditClassList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested auditClasses.
func (c *FakeAuditClasses) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewRootWatchAction(auditclassesResource, opts))
}

// Create takes the representation of a auditClass and creates it.  Returns the server's representation of the auditClass, and an error, if there is any.
func (c *FakeAuditClasses) Create(auditClass *auditregistration.AuditClass) (result *auditregistration.AuditClass, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootCreateAction(auditclassesResource, auditClass), &auditregistration.AuditClass{})
	if obj == nil {
		return nil, err
	}
	return obj.(*auditregistration.AuditClass), err
}

// Update takes the representation of a auditClass and updates it. Returns the server's representation of the auditClass, and an error, if there is any.
func (c *FakeAuditClasses) Update(auditClass *auditregistration.AuditClass) (result *auditregistration.AuditClass, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateAction(auditclassesResource, auditClass), &auditregistration.AuditClass{})
	if obj == nil {
		return nil, err
	}
	return obj.(*auditregistration.AuditClass), err
}

// Delete takes name of the auditClass and deletes it. Returns an error if one occurs.
func (c *FakeAuditClasses) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewRootDeleteAction(auditclassesResource, name), &auditregistration.AuditClass{})
	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeAuditClasses) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewRootDeleteCollectionAction(auditclassesResource, listOptions)

	_, err := c.Fake.Invokes(action, &auditregistration.AuditClassList{})
	return err
}

// Patch applies the patch and returns the patched auditClass.
func (c *FakeAuditClasses) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *auditregistration.AuditClass, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootPatchSubresourceAction(auditclassesResource, name, pt, data, subresources...), &auditregistration.AuditClass{})
	if obj == nil {
		return nil, err
	}
	return obj.(*auditregistration.AuditClass), err
}
